/**
 * Reading the geometry container.
 *
 * The central fixture is **bytes the conversion service actually produced**,
 * not bytes this file made up. A reader and a writer tested separately against
 * the same assumption both pass while disagreeing with each other; the only
 * thing that catches that is running one against the other's output. The same
 * reasoning put the real demo host into `protocol-conversation.spec.ts`.
 *
 * Its header happens to be 319 bytes, so the 4-byte alignment padding is one
 * byte rather than zero — the case a round number would quietly skip.
 */
import { describe, expect, it } from 'vitest';

import {
  ModelGeometryFormatError,
  decodeGeometryContainer,
} from './model-geometry';

/**
 * Generated by `encode_geometry_container` in converter/app.py, from two
 * synthetic buckets: IfcWall with 4 vertices and 2 triangles, IfcWindow with
 * 3 vertices and 1 triangle. Regenerate this if the container layout changes
 * — that is the point of it.
 */
const REAL_CONTAINER_BASE64 =
  'Q0RFRwEAAAA/AQAAeyJzdWNjZXNzIjp0cnVlLCJ0eXBlIjoiaWZjM2QiLCJncm91cHMiOlt7InR5cGUiOiJJZmNXYWxsIiwi'
  + 'c3RhcnQiOjAsImNvdW50Ijo2LCJjb2xvciI6WzAuODUsMC44MiwwLjc4XSwib3BhY2l0eSI6MS4wfSx7InR5cGUiOiJJZmNX'
  + 'aW5kb3ciLCJzdGFydCI6NiwiY291bnQiOjMsImNvbG9yIjpbMC41NSwwLjc1LDAuOV0sIm9wYWNpdHkiOjAuNX1dLCJ2ZXJ0'
  + 'ZXhDb3VudCI6NywidHJpYW5nbGVDb3VudCI6MywiYm91bmRzIjp7Im1pbiI6WzAuMCwxLjAsMi4wXSwibWF4IjpbOS4wLDEw'
  + 'LjAsMTEuMF19LCJlbGVtZW50Q291bnQiOjIsInNjaGVtYSI6IklGQzQifQAAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBA'
  + 'AADgQAAAAEEAABBBAAAgQQAAMEEAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAAAAAAAAAAAAAAAAAAAAA'
  + 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  + 'AQAAAAIAAAABAAAAAgAAAAMAAAAEAAAABQAAAAYAAAA=';

function realContainer(): ArrayBuffer {
  const binary = atob(REAL_CONTAINER_BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes.buffer;
}

/** A container built here, so a field can be varied deliberately. */
function containerWith(header: Record<string, unknown>,
                       buffers: { positions: number[]; normals: number[]; indices: number[] }) {
  const headerBytes = new TextEncoder().encode(JSON.stringify(header));
  const padding = ((-headerBytes.length) % 4 + 4) % 4;
  const bodyBytes = (buffers.positions.length + buffers.normals.length
                     + buffers.indices.length) * 4;
  const buffer = new ArrayBuffer(12 + headerBytes.length + padding + bodyBytes);
  const view = new DataView(buffer);

  new Uint8Array(buffer, 0, 4).set(new TextEncoder().encode('CDEG'));
  view.setUint32(4, 1, true);
  view.setUint32(8, headerBytes.length, true);
  new Uint8Array(buffer, 12, headerBytes.length).set(headerBytes);

  let offset = 12 + headerBytes.length + padding;
  new Float32Array(buffer, offset, buffers.positions.length).set(buffers.positions);
  offset += buffers.positions.length * 4;
  new Float32Array(buffer, offset, buffers.normals.length).set(buffers.normals);
  offset += buffers.normals.length * 4;
  new Uint32Array(buffer, offset, buffers.indices.length).set(buffers.indices);

  return buffer;
}

describe('reading a container the conversion service wrote', () => {

  it('recovers every vertex position', () => {
    const geometry = decodeGeometryContainer(realContainer());

    expect(geometry.vertexCount).toBe(7);
    expect(geometry.positions).toHaveLength(21);
    // IfcWall's four vertices, then IfcWindow's three, each numbered from 0
    // by the fixture's generator.
    expect(Array.from(geometry.positions.slice(0, 6)))
      .toEqual([0, 1, 2, 3, 4, 5]);
  });

  it('recovers the triangle indices already shifted into the merged buffer', () => {
    // The whole reason the shift exists: IfcWindow's own triangle is 0,1,2
    // but it must index past IfcWall's four vertices once merged.
    const geometry = decodeGeometryContainer(realContainer());

    expect(Array.from(geometry.indices)).toEqual([0, 1, 2, 1, 2, 3, 4, 5, 6]);
  });

  it('recovers one group per element type, in index units', () => {
    const geometry = decodeGeometryContainer(realContainer());

    expect(geometry.groups.map((group) => [group.type, group.start, group.count]))
      .toEqual([['IfcWall', 0, 6], ['IfcWindow', 6, 3]]);
  });

  it('keeps glazing translucent', () => {
    const geometry = decodeGeometryContainer(realContainer());
    const window = geometry.groups.find((group) => group.type === 'IfcWindow');

    expect(window?.opacity).toBe(0.5);
  });

  it('carries no colour buffer, because colour is per type', () => {
    // Positions and normals only. If a third float buffer reappears the
    // arithmetic below stops matching the payload.
    const geometry = decodeGeometryContainer(realContainer());

    expect(geometry.positions.length).toBe(geometry.vertexCount * 3);
    expect(geometry.normals.length).toBe(geometry.vertexCount * 3);
    expect(geometry.indices.length).toBe(geometry.triangleCount * 3);
  });

  it('recovers the model metadata the panel displays', () => {
    const geometry = decodeGeometryContainer(realContainer());

    expect(geometry.schema).toBe('IFC4');
    expect(geometry.elementCount).toBe(2);
    expect(geometry.bounds.min).toHaveLength(3);
  });
});

describe('refusing what it cannot read', () => {

  it('rejects a buffer that is not geometry at all', () => {
    const notGeometry = new TextEncoder().encode('<!doctype html><html>…').buffer;

    expect(() => decodeGeometryContainer(notGeometry))
      .toThrow(ModelGeometryFormatError);
  });

  it('rejects a newer container rather than misreading it', () => {
    // A future writer may reorder buffers. Reading one with this reader would
    // produce a plausible-looking wrong building, so the version is checked.
    const buffer = realContainer();
    new DataView(buffer).setUint32(4, 2, true);

    expect(() => decodeGeometryContainer(buffer)).toThrow(/version 2/);
  });

  it('rejects a truncated body instead of drawing half a building', () => {
    const full = realContainer();
    const truncated = full.slice(0, full.byteLength - 40);

    expect(() => decodeGeometryContainer(truncated)).toThrow(/truncated/);
  });

  it('rejects an empty response', () => {
    expect(() => decodeGeometryContainer(new ArrayBuffer(0)))
      .toThrow(ModelGeometryFormatError);
  });

  it('names what it found, so the failure is diagnosable', () => {
    const notGeometry = new TextEncoder().encode('{"success":false}').buffer;

    expect(() => decodeGeometryContainer(notGeometry)).toThrow(/CDEG/);
  });
});

describe('alignment', () => {

  // Float32Array throws on a byteOffset that is not a multiple of four, so
  // every header length modulo 4 has to land the buffers on a boundary. One
  // example cannot show that; these four cover the residues.
  for (const padding of [0, 1, 2, 3]) {
    it(`reads a container whose header needs ${padding} bytes of padding`, () => {
      // `schema` is the only free-length field, so it is what tunes the
      // header to each residue.
      let schema = 'IFC4';
      let buffer = containerWith(
        { success: true, type: 'ifc3d', groups: [], vertexCount: 1, triangleCount: 1,
          elementCount: 0, schema, bounds: { min: [0, 0, 0], max: [1, 1, 1] } },
        { positions: [1, 2, 3], normals: [0, 0, 1], indices: [0, 0, 0] });

      // Grow the schema string until the header length hits this residue.
      while ((new DataView(buffer).getUint32(8, true) % 4) !== (4 - padding) % 4) {
        schema += 'X';
        buffer = containerWith(
          { success: true, type: 'ifc3d', groups: [], vertexCount: 1, triangleCount: 1,
            elementCount: 0, schema, bounds: { min: [0, 0, 0], max: [1, 1, 1] } },
          { positions: [1, 2, 3], normals: [0, 0, 1], indices: [0, 0, 0] });
      }

      const geometry = decodeGeometryContainer(buffer);

      expect(Array.from(geometry.positions)).toEqual([1, 2, 3]);
      expect(Array.from(geometry.indices)).toEqual([0, 0, 0]);
    });
  }
});

/**
 * How a group's element count survives a container that predates it.
 *
 * <p>`elementCount` was added to the group table after the format shipped, and
 * the decoder spreads the header straight into its result. Without a default
 * the field would be `undefined` while the type says `number` — and the model
 * tree reads it to decide whether to show a quantity, so the lie would surface
 * as `×undefined` beside an element type rather than as a type error anyone
 * would catch.
 */
describe('a group written before element counts existed', () => {

  /** The group table as the first version of the writer emitted it. */
  const withoutCounts = [
    { type: 'IfcWall', start: 0, count: 3, color: [0.85, 0.82, 0.78], opacity: 1.0 },
  ];

  function decodeWith(groups: unknown[]) {
    return decodeGeometryContainer(containerWith(
      { success: true, type: 'ifc3d', groups, vertexCount: 1, triangleCount: 1,
        elementCount: 1, schema: 'IFC4', bounds: { min: [0, 0, 0], max: [1, 1, 1] } },
      { positions: [1, 2, 3], normals: [0, 0, 1], indices: [0, 0, 0] }));
  }

  it('reads as zero rather than undefined', () => {
    const [group] = decodeWith(withoutCounts).groups;

    expect(group!.elementCount).toBe(0);
  });

  it('leaves everything else on the group untouched', () => {
    const [group] = decodeWith(withoutCounts).groups;

    expect(group!.type).toBe('IfcWall');
    expect(group!.start).toBe(0);
    expect(group!.count).toBe(3);
    expect(group!.opacity).toBe(1);
  });

  it('keeps a count the writer did send', () => {
    const [group] = decodeWith(
      [{ ...withoutCounts[0], elementCount: 31 }]).groups;

    expect(group!.elementCount).toBe(31);
  });
});
